from models_app.admin.user.resources import UserAdmin
from models_app.admin.access.resources import AccessAdmin
from models_app.admin.page.resources import PageAdmin
from models_app.admin.block.resources import Block
from models_app.admin.blocks.text_block.resources import TextBlock
from models_app.admin.blocks.callout_block.resources import CalloutBlock
from models_app.admin.blocks.image_block.resources import ImageBlock
from models_app.admin.blocks.link_block.resources import LinkBlock
from models_app.admin.blocks.divider_block.resources import DividerBlock
