# Generated by Django 4.0 on 2023-07-05 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', related_query_name='block', to='models_app.page', verbose_name='Страница')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'db_table': 'blocks',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CalloutBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_app.block')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='callout_image_block/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Блок с картинкой и текстом',
                'verbose_name_plural': 'Блоки с картинкой и текстом',
                'db_table': 'callout_blocks',
            },
            bases=('models_app.block',),
        ),
        migrations.CreateModel(
            name='DividerBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_app.block')),
            ],
            options={
                'verbose_name': 'Блок с отступом',
                'verbose_name_plural': 'Блоки с отступом',
                'db_table': 'divider_blocks',
            },
            bases=('models_app.block',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_app.block')),
                ('image', models.ImageField(upload_to='image_block/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Блок с картинкой',
                'verbose_name_plural': 'Блоки с картинкой',
                'db_table': 'image_blocks',
            },
            bases=('models_app.block',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_app.block')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('TEXT', 'Текст'), ('CODE', 'Текст с кодом'), ('HEADER_TEXT', 'Заголовок'), ('QUOTE_TEXT', 'Поясняющий блок')], default='TEXT', max_length=11, verbose_name='Тип блока')),
            ],
            options={
                'verbose_name': 'Блок с текстом',
                'verbose_name_plural': 'Блоки с текстом',
                'db_table': 'text_blocks',
            },
            bases=('models_app.block',),
        ),
        migrations.CreateModel(
            name='LinkBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models_app.block')),
                ('page_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.page', verbose_name='Страница (ссылка)')),
            ],
            options={
                'verbose_name': 'Блок с ссылкой',
                'verbose_name_plural': 'Блоки с ссылкой',
                'db_table': 'line_blocks',
            },
            bases=('models_app.block',),
        ),
    ]
