# Generated by Django 4.0 on 2023-07-18 12:19
import os.path

from django.db import migrations
from django.db.migrations import RunPython

from conf.settings.django import env, BASE_DIR


def main_page(apps, schema_editor):
    Page = apps.get_model("models_app", "Page")
    main, create = Page.objects.get_or_create(
        id=env("MAIN_PAGE_UUID", cast=str),
        name="Главная страница",
    )
    Page.objects.get_or_create(
        id=env("PYTHON_BASIC_UUID", cast=str),
        name="Python основы",
        parent_page=main,
        icon=os.path.join(BASE_DIR, 'media', 'image_page', 'python.png')
    )
    Page.objects.get_or_create(
        id=env("PYTHON_OOP_UUID", cast=str),
        name="Python ООП",
        parent_page=main,
        icon=os.path.join(BASE_DIR, 'media', 'image_page', 'python_oop.png')
    )
    Page.objects.get_or_create(
        id=env("DJANGO_UUID", cast=str),
        name="Django",
        parent_page=main,
        icon=os.path.join(BASE_DIR, 'media', 'image_page', 'django.png')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        RunPython(main_page),
    ]
