# Generated by Django 4.0 on 2023-07-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_block_calloutblock_dividerblock_imageblock_textblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblock',
            name='page_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='models_app.page', verbose_name='Страница (ссылка)'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('CODE', 'Текст с кодом'), ('HEADERTEXT', 'Заголовок'), ('QUOTETEXT', 'Поясняющий блок')], default='TEXT', max_length=11, verbose_name='Тип блока'),
        ),
    ]
