# Generated by Django 4.0 on 2024-08-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_page_created_at_page_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='Находится на главной странице'),
        ),
    ]
