# Generated by Django 4.0 on 2023-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_page_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image_page/', verbose_name='Иконка'),
        ),
    ]
